#include "stubs_asm.h"
DEF(playrec_mode,                   0x00003cc0)  //*sub_FF0A34E4 

DEF(file_counter_var,               0x8ce4)      //*loc_FF1F38AC

DEF(active_palette_buffer,          0x72d4+0x8)  // 
DEF(palette_buffer_ptr,             0x72d4+0x2c) //*sub_FF19CBC0

DEF(active_viewport_buffer,         0x2167c+0x3c)//*sub_FF04EFEC + loc_FF04F4A8

DEF(viewport_buffers,               0xFF6B20B4)  //*

DEF(bitmap_buffer,                  0x41a0+0x30) //*sub_FF0B83A0
DEF(active_bitmap_buffer,           0x41a0+0x28) //*sub_FF0B7624

DEF(recreview_hold,                 0xce10+0x1c) //*sub_FF2994A8

DEF(_nrflag,                        0xe20c)      //*sub_FF2EF1F8 





