--[[
@title hostlua misc test
@chdk_version 1.7.0
--]]
--[[
test various camera_funcs functions
usage
from tools/hostlua/emu run
../lua emu.lua test/misc.lua -modroot=../../../CHDK
]]
props=require'propcase'
-- functions added / changed around r6301
set_focus_interlock_bypass(1)
local dof=get_dofinfo()
assert(get_focal_length() == dof.focal_length)
assert(get_eff_focal_length() == dof.eff_focal_length)
assert(get_current_av96() == get_av96())
assert(get_current_tv96() == get_tv96())
assert(get_current_base_sv96() == 795)
assert(get_current_delta_sv96() == 96)
assert(get_max_av96() == 664)
assert(get_min_av96() == 192)
assert(get_nd_value_ev96() == 288)
set_nd_filter(1)
assert(get_nd_current_ev96() == 288)
set_nd_filter(2)
assert(get_nd_current_ev96() == 0)
assert(get_canon_image_format() == 1)
set_canon_image_format(3)
assert(get_canon_image_format() == 3)
assert(get_canon_raw_support() == true)
set_record(0)
assert(get_imager_active() == false)
set_record(1)
assert(get_imager_active() == true)
set_prop(123,0x616263)
assert(get_prop_str(123,1) == 'c')
assert(get_prop_str(123,3) == 'cba')
assert(get_prop_str(123,5) == 'cba\0\0')
assert(get_prop_str(9999,1) == false)
assert(set_prop_str(123,"12345") == true)
assert(get_prop_str(123,5) == "12345")
assert(get_prop(123) == 0x34333231)
set_clock(1999,12,31,23,59,59)
assert(screen_needs_refresh() == false)
assert(get_raw_support() == true)
assert(read_usb_msg() == nil)
assert(write_usb_msg('hi') == true)
force_analog_av(1)
usb_force_active(1)
assert(get_usb_capture_support() == 15)
assert(get_usb_capture_target() == 0)
assert(init_usb_capture(15) == true)
assert(get_usb_capture_target() == 15)
assert(get_nd_present() == 2)
poke(0xdeadbeef,1)
assert(get_flash_params_count() == 300)
local s,n = get_parameter_data(123)
assert(s=='')
assert(n==0)
assert(get_user_av_id() == 1)
set_user_av_by_id(4)
assert(get_user_av_id() == 4)
set_user_av_by_id_rel(-1)
assert(get_user_av_id() == 3)
assert(get_user_tv_id() == 1)
set_user_tv_by_id(2)
assert(get_user_tv_id() == 2)
set_user_tv_by_id_rel(3)
assert(get_user_tv_id() == 5)
assert(get_orientation_sensor() == 0)
swap_partitions(2)
md_af_led_control(100,20)

shut_down()
